development:
  adapter: postgresql
  encoding: unicode
  database: bill_tracker_development
  pool: 5
  username: jgaviria
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bill_tracker_test
  pool: 5
  username: jgaviria
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: bill_tracker_production
  pool: 5
  username: deploy
  password: